/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controller;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;

@WebServlet(urlPatterns = {"/home"})
public class App extends HttpServlet {
    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse response) throws IOException {
        String title = "WebApp";
        String name = "Jefferson de Moura Ferraz Lopes";
        String ra = "1460481821041";
        String teacher = "Fabricio Galende";

        req.setCharacterEncoding("UTF-8");
        response.setContentType("text/html");
        response.setCharacterEncoding("UTF-8");

        try {
            PrintWriter pw = response.getWriter();
            pw.print(new String("Título: ".getBytes(), StandardCharsets.UTF_8)
                    + title + "<br>" + "Nome/RA: " + name + " " + ra + "<br>" + "Professor: " + teacher);
            pw.close();
        } catch (IOException ioe) {
            System.out.println("Impossível escrever na resposta");
        }
    }
}
